name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DJANGO_SETTINGS_MODULE: bakerydemo.settings.dev
  NEXT_PUBLIC_WAGTAIL_API_HOST: http://localhost:8000

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
      - run: biome ci
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".node-version"
      - run: npm ci
      - run: npm run test

  render:
    needs: check
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: git clone --depth 1 --branch headless https://github.com/wagtail/bakerydemo.git bakerydemo
      - run: uv venv
        working-directory: bakerydemo
      - run: uv pip install -r requirements/base.txt
        working-directory: bakerydemo
      - run: |
          uv run manage.py migrate --noinput
          uv run manage.py load_initial_data
        working-directory: bakerydemo
      - run: |
          uv run manage.py runserver 0.0.0.0:8000 &
          sleep 3
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:8000/api/v2/pages/
        working-directory: bakerydemo

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".node-version"
      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_WAGTAIL_API_HOST: http://localhost:8000
